from __future__ import annotations

import json
from collections.abc import Iterable
from pathlib import Path

from .models import Obstacle


def _motion_data(obstacles: Iterable[Obstacle]) -> list[dict[str, object]]:
    obstacle_data = list(obstacles)
    for obstacle in obstacle_data:
        obstacle.validate_for_motion()
    return [obstacle.to_motion_dict() for obstacle in obstacle_data]


def export_json(path: str | Path, obstacles: Iterable[Obstacle], source_point_cloud: str = "") -> None:
    if not isinstance(source_point_cloud, str):
        raise ValueError("Source point cloud must be a string")
    payload = {
        "version": 1,
        "source_point_cloud": source_point_cloud,
        "obstacles": _motion_data(obstacles),
    }
    Path(path).write_text(json.dumps(payload, indent=2, ensure_ascii=False) + "\n", encoding="utf-8")


def export_python(path: str | Path, obstacles: Iterable[Obstacle]) -> None:
    obstacle_data = _motion_data(obstacles)
    serialized = json.dumps(obstacle_data, indent=4, ensure_ascii=False)
    content = f'''"""Generated by Galbot Motion Obstacle Annotator."""

import time

import galbot_sdk.g1 as gm
from galbot_sdk.g1 import GalbotMotion, GalbotRobot

OBSTACLES = {serialized}


def main():
    motion = GalbotMotion()
    robot = GalbotRobot()

    def printStatus(status):
        if status == gm.MotionStatus.SUCCESS:
            print("Result: SUCCESS")
        elif status == gm.MotionStatus.TIMEOUT:
            print("Result: TIMEOUT")
        elif status == gm.MotionStatus.FAULT:
            print("Result: FAULT")
        elif status == gm.MotionStatus.INVALID_INPUT:
            print("Result: INVALID_INPUT")
        elif status == gm.MotionStatus.INIT_FAILED:
            print("Result: INIT_FAILED")
        elif status == gm.MotionStatus.IN_PROGRESS:
            print("Result: IN_PROGRESS")
        elif status == gm.MotionStatus.STOPPED_UNREACHED:
            print("Result: STOPPED_UNREACHED")
        elif status == gm.MotionStatus.DATA_FETCH_FAILED:
            print("Result: DATA_FETCH_FAILED")
        elif status == gm.MotionStatus.PUBLISH_FAIL:
            print("Result: PUBLISH_FAIL")
        elif status == gm.MotionStatus.COMM_DISCONNECTED:
            print("Result: COMM_DISCONNECTED")

    if motion.init():
        print("GalbotMotion init OK")
    else:
        print("GalbotMotion init FAILED")
    if robot.init():
        print("GalbotRobot init OK")
    else:
        print("GalbotRobot init FAILED")

    time.sleep(2)
    try:
        for obstacle in OBSTACLES:
            status = motion.add_obstacle(
                obstacle_id=obstacle["obstacle_id"],
                obstacle_type=obstacle["obstacle_type"],
                pose=obstacle["pose"],
                scale=obstacle["scale"],
                target_frame=obstacle["target_frame"],
            )
            print(f"{{obstacle['obstacle_id']}}: ", end="")
            printStatus(status)
    finally:
        robot.request_shutdown()
        robot.wait_for_shutdown()
        robot.destroy()


if __name__ == "__main__":
    main()
'''
    Path(path).write_text(content, encoding="utf-8")
